#!/bin/bash

rm -rf aclocal.m4
rm -rf autom4te.cache
rm -rf config.h
rm -rf config.h.in
rm -rf config.log
rm -rf config.status
rm -rf configure
rm -rf depcomp
rm -rf install-sh
rm -rf Makefile
rm -rf Makefile.in
rm -rf missing
rm -rf stamp-h1

rm -rf doc/Makefile
rm -rf doc/Makefile.in

rm -rf src/Makefile.in
rm -rf src/Makefile
rm -rf src/*.o
rm -rf src/.deps
rm -rf src/tags
rm -rf src/svd
