name: build packages and custom image for openwrt 23.05.4

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: install prerequisites
        run: |
          sudo apt-get -q update
          sudo apt-get -y install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev python3-distutils python3-setuptools rsync swig unzip zlib1g-dev file wget liblua5.1-0-dev
 
      - name: obtains the sdk and the imagebuilder
        run: |
          curl https://downloads.openwrt.org/releases/23.05.4/targets/lantiq/xway/openwrt-sdk-23.05.4-lantiq-xway_gcc-12.3.0_musl.Linux-x86_64.tar.xz | tar -J -x
          curl https://downloads.openwrt.org/releases/23.05.4/targets/lantiq/xway/openwrt-imagebuilder-23.05.4-lantiq-xway.Linux-x86_64.tar.xz | tar -J -x
          
      - name: build packages
        run: |
          cd openwrt-sdk-*
          #adds this repository as a custom feed
          echo "src-git custom https://github.com/olivluca/danube-voip" >> feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          #use the sofia-sip from this repo instead of the one from the telephony feed
          #(which is compiled with --disable-stun)
          ./scripts/feeds uninstall sofia-sip
          ./scripts/feeds install -p custom -f sofia-sip
          make defconfig
          #ensure that the packages will be installed in bin
          echo "CONFIG_PACKAGE_svd=m" >> .config
          echo "CONFIG_PACKAGE_luci-app-svd=m" >> .config
          echo "CONFIG_PACKAGE_sofia-sip=m" >> .config
          #this will also build its dependencies
          make -j1 V=s package/luci-app-svd/compile
      - name: build custom image
        run: |
          # copy the packages just built to be used by the imagebuilder
          cp openwrt-sdk*/bin/packages/mips_24kc/custom/*.ipk openwrt-imagebuilder-*/packages/
          cd openwrt-imagebuilder-*
          # remove a lot of things so that svd and its dependencies fit
          make image PROFILE=arcadyan_arv7518pw PACKAGES="luci-app-svd -kmod-ppp -kmod-atm -kmod-pppoa -kmod-pppox -kmod-pppoe -ppp -ppp-mod-pppoa -ppp-mod-pppoe -kmod-ltq-adsl-danube -kmod-ltq-adsl-danube-mei -ltq-dsl-base -ltq-adsl-app -kmod-ltq-adsl-danube-fw-a -kmod-ltq-atm-danube -kmod-atm -linux-atm -kmod-ath9k  -kmod-ath9k-common -wireless-regdb -kmod-mac80211 -wpad-basic-mbedtls -hostapd-common -wpad -odhcpd-ipv6only -odhcp6c uhttpd -dnsmasq luci-theme-openwrt"          
      
      - uses: actions/Upload-artifact@v4
        with:
          name: packages-23.05.4
          path: openwrt-sdk-*/bin/packages/mips_24kc/custom/
          
      - uses: actions/Upload-artifact@v4
        with:
          name: image-23.05.4
          path: openwrt-imagebuilder-*/bin/

